export const frameworksData = [
  {
    id: 'playwright',
    title: '🎭 Playwright + TypeScript',
    subtitle: '58 Tests • Multi-Browser • HTML Reports',
    cardTitle: 'Playwright + TypeScript',
    cardSubtitle: 'TypeScript-first, cross-browser test suite targeting saucedemo.com',
    stats: ['29 tests', '2 browsers', '58 CI runs'],
    targets: [{ icon: 'language', name: 'saucedemo.com' }],
    features: [],
    factoryPattern: {
      title: 'Multi-Browser Execution Strategy',
      features: [
        { icon: 'blur_on', title: 'True Parallelism' },
        { icon: 'replay', title: 'Trace Capture' },
        { icon: 'storage', title: 'Centralised Fixtures' },
        { icon: 'sync_alt', title: 'CI/CD on Push & PR' },
        { icon: 'assessment', title: 'HTML Reports' },
        { icon: 'devices', title: 'Chromium + Firefox' },
      ],
    },
    cta: {
      href: 'https://github.com/mcello23/playwright-example',
      text: 'View on GitHub',
      icon: 'code',
    },
    report: {
      href: 'https://mcello23.github.io/playwright-example/',
      text: 'Live Report',
      icon: 'assessment',
    },
  },
  {
    id: 'cypress',
    title: '🌿 Cypress + TypeScript',
    subtitle: 'TypeScript • Mochawesome • cy.login()',
    cardTitle: 'Cypress + TypeScript',
    cardSubtitle: 'Typed spec files with reusable commands and Mochawesome reports',
    stats: ['28 tests', '5 specs', 'Cypress 14'],
    targets: [{ icon: 'language', name: 'saucedemo.com' }],
    features: [],
    factoryPattern: {
      title: 'TypeScript Spec Style',
      features: [
        { icon: 'code', title: 'TypeScript Specs' },
        { icon: 'lock', title: 'cy.login() Command' },
        { icon: 'assessment', title: 'Mochawesome Reports' },
        { icon: 'sync_alt', title: 'GitHub Actions CI' },
        { icon: 'videocam', title: 'Video Recording' },
        { icon: 'photo_camera', title: 'Failure Screenshots' },
      ],
    },
    cta: {
      href: 'https://github.com/mcello23/cypress-typescript-example',
      text: 'View on GitHub',
      icon: 'code',
    },
    report: {
      href: 'https://mcello23.github.io/cypress-typescript-example/',
      text: 'Live Report',
      icon: 'assessment',
    },
  },
  {
    id: 'cypress',
    title: '🌿 Cypress + Cucumber',
    subtitle: 'BDD • Gherkin • Allure',
    cardTitle: 'Cypress + Cucumber',
    cardSubtitle: 'Gherkin feature files with JavaScript step definitions',
    stats: ['27 scenarios', 'Gherkin', 'Allure'],
    targets: [{ icon: 'language', name: 'saucedemo.com' }],
    features: [],
    factoryPattern: {
      title: 'BDD / Gherkin Style',
      features: [
        { icon: 'description', title: 'Feature Files' },
        { icon: 'eco', title: 'Step Definitions' },
        { icon: 'insert_chart', title: 'Allure Reports' },
        { icon: 'sync_alt', title: 'CI/CD Pipeline' },
        { icon: 'shopping_cart', title: 'Cart & Checkout' },
        { icon: 'fact_check', title: 'Gherkin Scenarios' },
      ],
    },
    cta: {
      href: 'https://github.com/mcello23/cypress-with-cucumber-example',
      text: 'View on GitHub',
      icon: 'eco',
    },
    report: {
      href: 'https://mcello23.github.io/cypress-with-cucumber-example/',
      text: 'Live Report',
      icon: 'assessment',
    },
  },
  {
    id: 'selenium',
    title: '🔬 Selenium + Java',
    subtitle: 'Java 17 • JUnit 5 • Page Object Model',
    cardTitle: 'Selenium + Java 17',
    cardSubtitle: 'Clean POM architecture with JUnit 5 runner and Allure reporting',
    stats: ['12 tests', 'Java 17', 'Allure'],
    targets: [{ icon: 'language', name: 'saucedemo.com' }],
    features: [],
    factoryPattern: {
      title: 'JUnit 5 POM Suite',
      features: [
        { icon: 'layers', title: 'Clean POM' },
        { icon: 'fact_check', title: 'JUnit 5 Runner' },
        { icon: 'assessment', title: 'Allure Reports' },
        { icon: 'sync_alt', title: 'GitHub Actions CI' },
        { icon: 'lock', title: 'Login Flows' },
        { icon: 'shopping_cart', title: 'Checkout E2E' },
      ],
    },
    cta: {
      href: 'https://github.com/mcello23/selenium-java-example',
      text: 'View on GitHub',
      icon: 'code',
    },
  },
  {
    id: 'selenium',
    title: '🔬 Selenium + TestNG',
    subtitle: 'Java 17 • TestNG 7 • @DataProvider',
    cardTitle: 'Selenium + TestNG',
    cardSubtitle: '@DataProvider matrix covering all 5 saucedemo accounts',
    stats: ['7+ runs', '@DataProvider', 'Allure'],
    targets: [{ icon: 'language', name: 'saucedemo.com' }],
    features: [],
    factoryPattern: {
      title: 'TestNG Data-Driven Suite',
      features: [
        { icon: 'grid_view', title: '@DataProvider Matrix' },
        { icon: 'group', title: '5 User Accounts' },
        { icon: 'assessment', title: 'Allure Reports' },
        { icon: 'sync_alt', title: 'GitHub Actions CI' },
        { icon: 'visibility_off', title: 'Headless Chrome' },
        { icon: 'settings', title: 'WebDriverManager' },
      ],
    },
    cta: {
      href: 'https://github.com/mcello23/selenium-java-testng-example',
      text: 'View on GitHub',
      icon: 'grid_view',
    },
    report: {
      href: 'https://mcello23.github.io/selenium-java-testng-example/',
      text: 'Live Report',
      icon: 'assessment',
    },
  },
];
